version: "3.8"
services:
  redis:
    container_name: fsd_medic.redis
    image: redis:alpine
    expose:
      - "6379"
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s
  memcached:
    container_name: fsd_medic.memcached
    image: memcached:latest
    ports:
      - "11211:11211"
  prometheus:
    container_name: fsd_medic.prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml

    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
  grafana:
    container_name: fsd_medic.grafana
    image: grafana/grafana
    volumes:
      - grafana_storage:/var/lib/grafana
    ports:
      - "3000:3000"

  celery:
    build: .
    container_name: fsd_medic.celery
    command: poetry run celery -A fsd_medic worker --loglevel=info


  rabbitmq:
    container_name: fsd_medic.rabbitmq
    image: rabbitmq
    ports:
      - "5672:5672"
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics check_running -q" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 10s
  
  filebeat:
    container_name: fsd_medic.filebeat
    image: elastic/filebeat:8.9.2


  logstash:
    container_name: fsd_medic.logstash
    image: logstash:8.9.2
    volumes:
      - ./logstash.conf:/etc/prometheus/prometheus.yaml
    ports:
      - "5000:5000"

  elasticsearch:
    container_name: fsd_medic.elasticsearch
    image: elastic/elasticsearch:8.9.2
    ports:
      - "9200:9200"

  kibana:
    container_name: fsd_medic.kibana
    image: elastic/kibana:8.9.2



volumes:
  grafana_storage: {}

