filebeat.inputs:
- type: log
  enabled: true
  paths:
      - /var/log/nginx/access.log
  fields:
    type: nginx
  fields_under_root: true
  scan_frequency: 5s

output.logstash:
  hosts: ["fsd_medic.logstash:5000"]

setup.kibana:
  host: "fsd_medic.kibana:5601"
  
