# Generated by Django 5.0.1 on 2024-04-06 09:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('is_required', models.BooleanField(blank=True, default=False, verbose_name='Статус подтверждения')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Статус персонала')),
                ('online', models.BooleanField(default=False, verbose_name='Онлайн')),
                ('sex', models.CharField(default=None, max_length=255, null=True, verbose_name='Пол')),
                ('number', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Номер')),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Электронный адрес')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия')),
                ('surname', models.CharField(blank=True, max_length=40, null=True, verbose_name='Отчество')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('image', models.ImageField(blank=True, default=None, upload_to='users_photos/', verbose_name='Фотография Пользователья')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='Адрес')),
                ('verification_code', models.PositiveIntegerField(default=1, verbose_name='СМС код подтверждения')),
                ('reset_code', models.PositiveIntegerField(default=1, verbose_name='Код для сброса пароля')),
                ('number_verification_code', models.PositiveIntegerField(default=1, verbose_name='Код для привязки номера к аккаунту')),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название страны')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=100, verbose_name='Название Клиники')),
                ('password', models.CharField(max_length=128, null=True, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_required', models.BooleanField(default=False, verbose_name='Статус подтверждения')),
                ('rating', models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Рейтинг клиники')),
                ('description', models.TextField(blank=True, max_length=550, null=True, verbose_name='Описание клиники')),
                ('image', models.ImageField(blank=True, default='centers_photos/clinic_photo.jpg', upload_to='clinics_photos/', verbose_name='Фото клиники')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='Номер')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='Электронный адрес')),
                ('address', models.CharField(max_length=100, unique=True, verbose_name='Адрес')),
                ('review_date', models.DateTimeField(null=True, verbose_name='Предполагаемая дата и время интервью')),
                ('review_passed', models.BooleanField(null=True, verbose_name='Собеседование пройдено')),
                ('verification_code', models.PositiveIntegerField(default=1, verbose_name='СМС код подтверждения')),
                ('reset_code', models.PositiveIntegerField(default=1, verbose_name='Код для сброса пароля')),
                ('email_verification_code', models.PositiveIntegerField(default=0, verbose_name='Код для привязки почты к аккаунту')),
            ],
            options={
                'verbose_name': 'Клиника',
                'verbose_name_plural': 'Клиники',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название страны')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Заболевание',
                'verbose_name_plural': 'Заболевания',
            },
        ),
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('email', models.CharField(max_length=100, null=True, unique=True, verbose_name='Электронный адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name_plural': 'Лайки',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=40, null=True, verbose_name='Заголовок новости')),
                ('text', models.TextField(blank=True, max_length=500, null=True, verbose_name='Текст новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='NewsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='news_photos/news_photo.jpg', upload_to='news_photos/', verbose_name='Фото к новости')),
            ],
        ),
        migrations.CreateModel(
            name='NewsVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(default='news_photos/news_photo.jpg', upload_to='news_videos/', verbose_name='Видео к новости')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('title', models.CharField(max_length=255, verbose_name='Название записи')),
                ('online', models.BooleanField(default=False, verbose_name='Онлайн')),
                ('time_start', models.DateTimeField(blank=True, null=True, verbose_name='Начало ')),
                ('time_end', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('notify', models.DateTimeField(blank=True, null=True, verbose_name='Время уведомления о записи')),
                ('problem', models.CharField(blank=True, max_length=255, null=True, verbose_name='Причина')),
                ('duration_note', models.IntegerField(blank=True, null=True, verbose_name='Длительность')),
                ('file', models.FileField(blank=True, null=True, upload_to='files_to_notes/', verbose_name='Файлы к записи')),
                ('special_check', models.BooleanField(default=False, verbose_name='Доп. проверка специалистов')),
                ('status', models.CharField(choices=[('Passed', 'Подтверждена'), ('In processing', 'На рассмотрении'), ('Rejected', 'Отклонена')], default='In processing', max_length=255, verbose_name='Статус записи')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.CreateModel(
            name='NumberCode',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('number', models.CharField(max_length=30, null=True, unique=True, verbose_name='Номер')),
            ],
        ),
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Сохранение',
                'verbose_name_plural': 'Сохраненное',
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('access_accept', models.ManyToManyField(related_name='access', to=settings.AUTH_USER_MODEL, verbose_name='Доступ (принятые)')),
                ('access_unaccept', models.ManyToManyField(related_name='unaccept', to=settings.AUTH_USER_MODEL, verbose_name='Доступ (непринятые)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доступ',
                'verbose_name_plural': 'Доступ',
            },
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название центра')),
                ('password', models.CharField(max_length=128, null=True, verbose_name='Пароль')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Последний вход')),
                ('image', models.ImageField(blank=True, default='centers_photos/center_photo.jpg', upload_to='centers_photos/', verbose_name='Фото центра')),
                ('rating', models.FloatField(default=5, max_length=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Рейтинг центра')),
                ('description', models.TextField(blank=True, max_length=550, null=True, verbose_name='Описание центра')),
                ('is_required', models.BooleanField(default=False, verbose_name='Статус подтверждения')),
                ('number', models.CharField(max_length=30, null=True, unique=True, verbose_name='Номер')),
                ('email', models.CharField(max_length=100, null=True, unique=True, verbose_name='Электронный адрес')),
                ('observed', models.IntegerField(default=100, verbose_name='Наблюдается')),
                ('observed_after', models.IntegerField(default=100, verbose_name='Наблюдалось')),
                ('address', models.CharField(max_length=100, null=True, unique=True, verbose_name='Адрес')),
                ('lng', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='Долгота')),
                ('lat', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='Широта')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата Изменения')),
                ('review_date', models.DateTimeField(null=True, verbose_name='Предполагаемая дата и время интервью')),
                ('review_passed', models.BooleanField(null=True, verbose_name='Собеседование пройдено')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin', to=settings.AUTH_USER_MODEL, verbose_name='Администратор центра')),
            ],
            options={
                'verbose_name': 'Центр',
                'verbose_name_plural': 'Центры',
            },
        ),
    ]
