# Generated by Django 4.2.4 on 2023-09-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_doctor', '__first__'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='employees',
            field=models.ManyToManyField(related_name='employees', to='auth_doctor.doctor', verbose_name='Сотрудники'),
        ),
    ]
