# Generated by Django 4.2.1 on 2023-07-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_code',
            field=models.PositiveIntegerField(default=1, verbose_name='Код для привязки почты к аккаунту'),
        ),
    ]
