# Generated by Django 4.2.4 on 2023-09-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='observed',
            field=models.IntegerField(default=100),
        ),
    ]
