# Generated by Django 5.0.1 on 2024-04-06 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('auth_doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='employees',
            field=models.ManyToManyField(related_name='employees', to='auth_doctor.doctor', verbose_name='Сотрудники'),
        ),
        migrations.AddField(
            model_name='user',
            name='centers',
            field=models.ManyToManyField(blank=True, to='api.center', verbose_name='Центр'),
        ),
        migrations.AddField(
            model_name='center',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_clinic', to=settings.AUTH_USER_MODEL, verbose_name='Администартор'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.center', verbose_name='Центры'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='employees',
            field=models.ManyToManyField(related_name='clinic_employees', to='auth_doctor.doctor', verbose_name='Сотрудники'),
        ),
        migrations.AddField(
            model_name='user',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_clinic', to='api.clinic', verbose_name='Клиника'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='center',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='supported_diseases',
            field=models.ManyToManyField(to='api.disease', verbose_name='Изученные заболевания'),
        ),
        migrations.AddField(
            model_name='center',
            name='supported_diseases',
            field=models.ManyToManyField(to='api.disease', verbose_name='Поддерживаемые заболевания'),
        ),
        migrations.AddField(
            model_name='user',
            name='disease',
            field=models.ManyToManyField(blank=True, to='api.disease', verbose_name='Заболевания'),
        ),
        migrations.AddField(
            model_name='user',
            name='interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interest', to='api.disease', verbose_name='Интерес к заболеванию'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='news',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.clinic', verbose_name='Клиника'),
        ),
        migrations.AddField(
            model_name='news',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.disease', verbose_name='Заболевание'),
        ),
        migrations.AddField(
            model_name='like',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.news', verbose_name='Новость'),
        ),
        migrations.AddField(
            model_name='newsimages',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_images', to='api.news'),
        ),
        migrations.AddField(
            model_name='newsvideos',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_videos', to='api.news'),
        ),
        migrations.AddField(
            model_name='note',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.center'),
        ),
        migrations.AddField(
            model_name='note',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.clinic'),
        ),
        migrations.AddField(
            model_name='note',
            name='doctors',
            field=models.ManyToManyField(to='auth_doctor.doctor', verbose_name='Врачи'),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='saved',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.news', verbose_name='Новость'),
        ),
        migrations.AddField(
            model_name='saved',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.clinic'),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='main_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_doctor.doctor'),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
