# Generated by Django 4.2.1 on 2023-06-07 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centers',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.countries', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='user',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.centers', verbose_name='Центр'),
        ),
    ]
