# Generated by Django 4.2.1 on 2023-06-20 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Описание фотографии')),
                ('image', models.ImageField(blank=True, upload_to='site_photos/', verbose_name='Фотография Сайта')),
            ],
        ),
        migrations.RemoveField(
            model_name='url_params',
            name='interview',
        ),
        migrations.RemoveField(
            model_name='url_params',
            name='user',
        ),
        migrations.AddField(
            model_name='url_params',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.groups'),
        ),
    ]
