# Generated by Django 4.2.4 on 2023-09-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_center_observed'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='observed_after',
            field=models.IntegerField(default=100, verbose_name='Наблюдалось'),
        ),
        migrations.AlterField(
            model_name='center',
            name='observed',
            field=models.IntegerField(default=100, verbose_name='Наблюдается'),
        ),
    ]
