# Generated by Django 4.2.4 on 2023-09-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_center_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='employees_number',
        ),
    ]
