# Generated by Django 4.2.4 on 2023-10-03 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="interest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interest",
                to="api.disease",
                verbose_name="Интерес к заболеванию",
            ),
        ),
    ]
