# Generated by Django 4.2.1 on 2023-07-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_center_user_centers_user_main_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='special_check',
            field=models.BooleanField(default=False, verbose_name='Доп. проверка специалистов'),
        ),
    ]
