# Generated by Django 4.2.4 on 2023-09-20 09:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_center_observed_after_alter_center_observed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_accept',
            field=models.ManyToManyField(blank=True, null=True, related_name='accept', to=settings.AUTH_USER_MODEL, verbose_name='Доступ (принятые)'),
        ),
        migrations.AddField(
            model_name='user',
            name='access_unaccept',
            field=models.ManyToManyField(blank=True, null=True, related_name='unaccept', to=settings.AUTH_USER_MODEL, verbose_name='Доступ (непринятые)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
