# Generated by Django 4.2.1 on 2023-06-20 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_images_remove_url_params_interview_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.AlterModelOptions(
            name='url_params',
            options={'verbose_name': 'Параметер', 'verbose_name_plural': 'Параметры'},
        ),
        migrations.AlterField(
            model_name='url_params',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.groups', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='url_params',
            name='parameter',
            field=models.CharField(max_length=50, verbose_name='Параметер'),
        ),
    ]
