# Generated by Django 4.2.4 on 2023-09-30 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_doctor', '__first__'),
        ('api', '0003_remove_center_employees_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='supported_diseases',
            field=models.ManyToManyField(to='api.disease', verbose_name='Изученные заболевания'),
        ),
        migrations.AlterField(
            model_name='note',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_doctor', to='auth_doctor.doctor', verbose_name='Врач'),
        ),
    ]
