# Generated by Django 5.0.1 on 2024-05-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_clinic_admin_firstname_clinic_admin_lastname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="admin_number",
            field=models.CharField(
                blank=True, max_length=220, verbose_name="Номер админа"
            ),
        ),
    ]
