# Generated by Django 4.2.4 on 2023-10-04 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_interest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interview',
        ),
    ]
