# Generated by Django 4.2.4 on 2023-09-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_center_observed_after_alter_center_observed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verify',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Подтверждение почты'),
        ),
    ]
