# Generated by Django 4.2.1 on 2023-07-18 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_family'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='translate',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='translate_from',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='translate_to',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='users_to_note',
        ),
        migrations.RemoveField(
            model_name='user',
            name='family',
        ),
        migrations.AddField(
            model_name='notes',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
