# Generated by Django 4.2.4 on 2023-09-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_doctor', '__first__'),
        ('api', '0004_alter_clinic_supported_diseases_alter_note_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='employees_number',
        ),
        migrations.AddField(
            model_name='clinic',
            name='employees',
            field=models.ManyToManyField(related_name='clinic_employees', to='auth_doctor.doctor', verbose_name='Сотрудники'),
        ),
    ]
