# Generated by Django 4.2.1 on 2023-06-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_url_params_options_alter_url_params_group_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centers',
            options={'verbose_name': 'Центр', 'verbose_name_plural': 'Центры'},
        ),
        migrations.AlterModelOptions(
            name='countries',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='country_codes',
            options={'verbose_name': 'Номерной код', 'verbose_name_plural': 'Номерные коды'},
        ),
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='interviews',
            options={'verbose_name': 'Интервью', 'verbose_name_plural': 'Интервью'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='url_params',
            options={'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки для регистрации'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RenameField(
            model_name='url_params',
            old_name='group_id',
            new_name='group',
        ),
        migrations.AlterField(
            model_name='url_params',
            name='parameter',
            field=models.CharField(max_length=50, verbose_name='Ссылка'),
        ),
    ]
