# Generated by Django 4.2.4 on 2023-09-20 09:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_access_accept_user_access_unaccept_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_accept',
            field=models.ManyToManyField(blank=True, related_name='accept', to=settings.AUTH_USER_MODEL, verbose_name='Доступ (принятые)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='access_unaccept',
            field=models.ManyToManyField(blank=True, related_name='unaccept', to=settings.AUTH_USER_MODEL, verbose_name='Доступ (непринятые)'),
        ),
    ]
