# Generated by Django 5.0.1 on 2024-05-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_clinic_admin_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinic",
            name="email",
            field=models.CharField(
                default=None,
                max_length=100,
                unique=True,
                verbose_name="Электронный адрес",
            ),
        ),
    ]
