# Generated by Django 4.2.1 on 2023-07-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_centers_lat_centers_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centers',
            name='lat',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='centers',
            name='lon',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
    ]
