# Generated by Django 4.2.1 on 2023-06-22 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_images_alter_centers_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countries',
            options={'verbose_name': 'Страну', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': 'Группу', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='saved',
            options={'verbose_name': 'Сохранение', 'verbose_name_plural': 'Сохраненное'},
        ),
        migrations.AlterModelOptions(
            name='url_params',
            options={'verbose_name': 'Ссылку', 'verbose_name_plural': 'Ссылки для регистрации'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'Пользователья', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='centers',
            name='coordinate_latitude',
        ),
        migrations.RemoveField(
            model_name='centers',
            name='coordinate_longitude',
        ),
        migrations.AddField(
            model_name='centers',
            name='coordinate',
            field=models.FloatField(null=True, verbose_name='Координаты'),
        ),
        migrations.CreateModel(
            name='Clinics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Название Клиники')),
                ('is_required', models.BooleanField(default=False, verbose_name='Статус подтверждения')),
                ('number', models.CharField(max_length=30, null=True, unique=True, verbose_name='Номер')),
                ('email', models.CharField(max_length=100, null=True, unique=True, verbose_name='Электронный адрес')),
                ('employees_number', models.IntegerField(null=True, verbose_name='Число Сотрудников')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('address', models.CharField(max_length=100, null=True, unique=True, verbose_name='Адрес')),
                ('coordinate', models.FloatField(null=True, verbose_name='Координаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата Изменения')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.countries', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Клинику',
                'verbose_name_plural': 'Клиники',
            },
        ),
    ]
