# Generated by Django 4.2.1 on 2023-07-25 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_centers_lat_alter_centers_lon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centers',
            old_name='lon',
            new_name='lng',
        ),
    ]
