# Generated by Django 5.0.1 on 2024-06-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_clinic_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicAdmin',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('admin_firstname', models.CharField(blank=True, max_length=220, verbose_name='Имя админа')),
                ('admin_surname', models.CharField(blank=True, max_length=220, verbose_name='Фамилия админа')),
                ('admin_lastname', models.CharField(blank=True, max_length=220, verbose_name='Отчество админа')),
                ('admin_number', models.CharField(blank=True, max_length=220, verbose_name='Номер админа')),
                ('admin_photo', models.ImageField(blank=True, default=None, upload_to='clinic_admin_photos/', verbose_name='Фото админа')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
