# Generated by Django 4.2.1 on 2023-06-22 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_clinics_delete_images_alter_centers_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinics',
            options={'verbose_name': 'Клинику', 'verbose_name_plural': 'Клиники'},
        ),
        migrations.AlterModelOptions(
            name='countries',
            options={'verbose_name': 'Страну', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': 'Группу', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='saved',
            options={'verbose_name': 'Сохранение', 'verbose_name_plural': 'Сохраненное'},
        ),
        migrations.AlterModelOptions(
            name='url_params',
            options={'verbose_name': 'Ссылку', 'verbose_name_plural': 'Ссылки для регистрации'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'Пользователья', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='clinics',
            name='address',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='clinics',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='clinics',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.countries', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='clinics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='clinics',
            name='email',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Электронный адрес'),
        ),
        migrations.AddField(
            model_name='clinics',
            name='employees_number',
            field=models.IntegerField(null=True, verbose_name='Число Сотрудников'),
        ),
        migrations.AddField(
            model_name='clinics',
            name='is_required',
            field=models.BooleanField(default=False, verbose_name='Статус подтверждения'),
        ),
        migrations.AddField(
            model_name='clinics',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Название Клиники'),
        ),
        migrations.AddField(
            model_name='clinics',
            name='number',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Номер'),
        ),
        migrations.AddField(
            model_name='clinics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата Изменения'),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='Город'),
        ),
    ]
