# Generated by Django 4.2.4 on 2023-09-21 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_access_accept_alter_user_access_unaccept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_accept',
        ),
        migrations.RemoveField(
            model_name='user',
            name='access_unaccept',
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('access_accept', models.ManyToManyField(related_name='access', to=settings.AUTH_USER_MODEL, verbose_name='Доступ (принятые)')),
                ('access_unaccept', models.ManyToManyField(related_name='unaccept', to=settings.AUTH_USER_MODEL, verbose_name='Доступ (непринятые)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
