# Generated by Django 4.2.1 on 2023-06-07 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0005_remove_user_groups_user_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviews',
            name='is_center_interview',
        ),
        migrations.RemoveField(
            model_name='interviews',
            name='is_doctor_interview',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_center_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_doctor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_patient',
        ),
        migrations.AddField(
            model_name='interviews',
            name='type',
            field=models.CharField(max_length=30, null=True, verbose_name='Тип интервью'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Группа'),
        ),
    ]
