# Generated by Django 4.2.4 on 2023-09-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Пол'),
        ),
    ]
