# Generated by Django 4.2.1 on 2023-06-28 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_clinics_options_alter_countries_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login',
        ),
    ]
