# Generated by Django 5.0.1 on 2024-06-08 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_clinicadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='admin_firstname',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='admin_lastname',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='admin_number',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='admin_surname',
        ),
    ]
