# Generated by Django 4.2.4 on 2023-09-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_user_access_accept_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'verbose_name': 'Доступ', 'verbose_name_plural': 'Доступ'},
        ),
    ]
