# Generated by Django 4.2.4 on 2023-10-07 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0007_clinic_email_verification_code_clinic_reset_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='city',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.city',
                                    verbose_name='Город'),
        ),
    ]
