# Generated by Django 5.0.1 on 2024-06-08 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_clinic_admin_remove_clinic_admin_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_clinic', to='api.clinicadmin', verbose_name='Администартор'),
        ),
    ]
