# Generated by Django 4.2.1 on 2023-08-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_notes_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hobby',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Интерес'),
        ),
    ]
