# Generated by Django 4.2.1 on 2023-06-09 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_centers_number_alter_interviews_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Название Группы')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='countries',
            name='number_length',
            field=models.CharField(max_length=2, null=True, verbose_name='Длина номера'),
        ),
        migrations.AlterField(
            model_name='centers',
            name='email',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Электронный адрес'),
        ),
        migrations.AlterField(
            model_name='centers',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Название Центра'),
        ),
        migrations.AlterField(
            model_name='interviews',
            name='email',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Электронный адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, unique=True, verbose_name='Электронный адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='api.groups', verbose_name='Группа'),
        ),
    ]
