# Generated by Django 4.2.4 on 2023-09-30 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_note_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Администартор'),
        ),
    ]
