# Generated by Django 5.0.1 on 2024-06-08 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_clinic_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='weekends',
        ),
    ]
