# Generated by Django 4.2.1 on 2023-07-04 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_emailcodes_numbercodes_delete_country_codes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.disease', verbose_name='Заболевание'),
        ),
    ]
