# Generated by Django 4.2.1 on 2023-08-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_notification'),
        ('api', '0008_user_hobby'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Centers',
            new_name='Center',
        ),
        migrations.RenameModel(
            old_name='Clinics',
            new_name='Clinic',
        ),
        migrations.RenameModel(
            old_name='Countries',
            new_name='Country',
        ),
        migrations.RenameModel(
            old_name='EmailCodes',
            new_name='EmailCode',
        ),
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
        migrations.RenameModel(
            old_name='Interviews',
            new_name='Interview',
        ),
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
        migrations.RenameModel(
            old_name='NumberCodes',
            new_name='NumberCode',
        ),
    ]
