# Generated by Django 4.2.1 on 2023-06-09 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_groups_remove_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='groups',
            new_name='group',
        ),
    ]
