# Generated by Django 4.2.6 on 2023-10-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_center_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="password",
            field=models.CharField(max_length=128, null=True, verbose_name="password"),
        ),
    ]
