# Generated by Django 4.2.1 on 2023-08-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_centers_center_rename_clinics_clinic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='users_photos/AccauntPreview.png', upload_to='users_photos/', verbose_name='Фотография Пользователья'),
        ),
    ]
