# Generated by Django 4.2.6 on 2023-10-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_clinic_last_login_clinic_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний вход'),
        ),
        migrations.AddField(
            model_name='center',
            name='password',
            field=models.CharField(max_length=128, null=True, verbose_name='Пароль'),
        ),
    ]
