# Generated by Django 4.2.1 on 2023-07-04 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='name',
            field=models.CharField(default=datetime.datetime(2023, 7, 4, 19, 9, 21, 574825, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
