# Generated by Django 5.0.1 on 2024-06-08 08:06

import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_clinic_weekends'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='workdays',
            field=django_mysql.models.ListCharField(models.CharField(max_length=2), blank=True, max_length=21, null=True, size=7),
        ),
    ]
