# Generated by Django 4.2.4 on 2023-09-30 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_clinic_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_clinic', to='api.clinic', verbose_name='Клиника'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_clinic', to=settings.AUTH_USER_MODEL, verbose_name='Администартор'),
        ),
    ]
