# Generated by Django 5.0.1 on 2024-06-08 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_clinic_workdays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='review_date',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='review_passed',
        ),
    ]
