# Generated by Django 4.2.6 on 2023-11-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_center_last_login_center_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinic",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
