# Generated by Django 4.2.1 on 2023-07-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_user_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='centers',
            name='description',
            field=models.TextField(blank=True, max_length=550, null=True, verbose_name='Описание центра'),
        ),
        migrations.AddField(
            model_name='centers',
            name='image',
            field=models.ImageField(blank=True, default='media/site_photos/center_photo.jpg', upload_to='centers_photos/', verbose_name='Фото центра'),
        ),
        migrations.AddField(
            model_name='centers',
            name='rating',
            field=models.FloatField(default=5, max_length=5, verbose_name='Рейтинг центра'),
        ),
        migrations.AlterField(
            model_name='centers',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название центра'),
        ),
    ]
