# Generated by Django 4.2.1 on 2023-07-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_user_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.PositiveIntegerField(default=1, verbose_name='СМС код подтверждения'),
        ),
    ]
