# Generated by Django 5.0.1 on 2024-06-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_clinic_review_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='employees',
        ),
        migrations.AddField(
            model_name='clinic',
            name='employees',
            field=models.IntegerField(default=0, verbose_name='Кол-во сотрудников'),
        ),
    ]
