# Generated by Django 4.2.1 on 2023-07-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_user_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='disease',
        ),
        migrations.AddField(
            model_name='user',
            name='disease',
            field=models.ManyToManyField(blank=True, null=True, to='api.disease', verbose_name='Заболевание'),
        ),
    ]
