# Generated by Django 5.0.1 on 2024-06-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_clinic_employees_clinic_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='worktime',
            field=models.IntegerField(default=0, verbose_name='Время активности на сайте (в минутах)'),
        ),
    ]
