# Generated by Django 4.2.1 on 2023-07-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_centers_description_centers_image_centers_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centers',
            name='image',
            field=models.ImageField(blank=True, default='centers_photos/center_photo.jpg', upload_to='centers_photos/', verbose_name='Фото центра'),
        ),
    ]
