# Generated by Django 4.2.1 on 2023-07-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_centers_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinics',
            options={'verbose_name': 'Клиника', 'verbose_name_plural': 'Клиники'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='clinics',
            name='description',
            field=models.TextField(blank=True, max_length=550, null=True, verbose_name='Описание клиники'),
        ),
        migrations.AddField(
            model_name='clinics',
            name='image',
            field=models.ImageField(blank=True, default='centers_photos/center_photo.jpg', upload_to='clinics_photos/', verbose_name='Фото клиники'),
        ),
        migrations.AddField(
            model_name='clinics',
            name='rating',
            field=models.FloatField(default=5, max_length=5, verbose_name='Рейтинг клиники'),
        ),
        migrations.AddField(
            model_name='clinics',
            name='supported_diseases',
            field=models.ManyToManyField(to='api.disease'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='site_photos/AccauntPreview.png', upload_to='users_photos/', verbose_name='Фотография Пользователя'),
        ),
    ]
