# Generated by Django 5.0.1 on 2024-06-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_clinic_worktime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicadmin',
            old_name='admin_firstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='clinicadmin',
            old_name='admin_lastname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='clinicadmin',
            old_name='admin_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='clinicadmin',
            old_name='admin_photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='clinicadmin',
            old_name='admin_surname',
            new_name='surname',
        ),
        migrations.AddField(
            model_name='clinicadmin',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения админа'),
        ),
    ]
