# Generated by Django 4.2.1 on 2023-07-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_clinics_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinics',
            name='description',
            field=models.TextField(blank=True, max_length=550, null=True, verbose_name='Описание центра'),
        ),
    ]
