# Generated by Django 4.2.4 on 2023-08-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_like_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователья', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='hobby',
        ),
        migrations.AddField(
            model_name='user',
            name='interest',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='Интерес к заболеванию'),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.BigAutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
