# Generated by Django 4.2.1 on 2023-07-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_user_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_code',
            field=models.PositiveIntegerField(default=1, verbose_name='Код для сброса пароля'),
        ),
    ]
