# Generated by Django 4.2.1 on 2023-06-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_country_codes_desease_news_saved_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='number_of_people',
            field=models.IntegerField(verbose_name='Количество людей'),
        ),
    ]
