# Generated by Django 5.0.1 on 2024-06-08 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_admin_firstname_clinicadmin_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_clinic', to='api.clinicadmin', verbose_name='Администартор'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='password'),
        ),
    ]
