# Generated by Django 4.2.1 on 2023-07-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_clinics_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinics',
            name='description',
            field=models.TextField(blank=True, max_length=550, null=True, verbose_name='Описание клиники'),
        ),
        migrations.AlterField(
            model_name='clinics',
            name='image',
            field=models.ImageField(blank=True, default='centers_photos/clinic_photo.jpg', upload_to='clinics_photos/', verbose_name='Фото клиники'),
        ),
    ]
