# Generated by Django 4.2.1 on 2023-07-07 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_clinics_description_alter_clinics_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centers',
            name='rating',
            field=models.FloatField(default=5, max_length=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Рейтинг центра'),
        ),
        migrations.AlterField(
            model_name='clinics',
            name='rating',
            field=models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Рейтинг клиники'),
        ),
    ]
