# Generated by Django 5.0.1 on 2024-06-20 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_clinicadmin_options_alter_saved_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
