# Generated by Django 4.2.1 on 2023-07-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_centers_rating_alter_clinics_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'Пользователья', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.PositiveIntegerField(default=1, verbose_name='СМС код подтверждения'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='disease',
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='media/site_photos/AccauntPreview.png', upload_to='users_photos/', verbose_name='Фотография Пользователья'),
        ),
        migrations.AddField(
            model_name='user',
            name='disease',
            field=models.ManyToManyField(blank=True, to='api.disease', verbose_name='Заболевание'),
        ),
    ]
