# Generated by Django 4.2.1 on 2023-06-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_like_options_user_desease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Логин'),
        ),
    ]
