# Generated by Django 4.2.1 on 2023-06-15 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_newsimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsImage',
        ),
    ]
