# Generated by Django 4.2.1 on 2023-07-12 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='disease',
            field=models.ManyToManyField(blank=True, to='api.disease', verbose_name='Заболевания'),
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate', models.BooleanField(default=False, verbose_name='Переводчик')),
                ('translate_from', models.CharField(blank=True, max_length=255, null=True, verbose_name='С какого языка')),
                ('translate_to', models.CharField(blank=True, max_length=255, null=True, verbose_name='На какой язык')),
                ('title', models.CharField(max_length=255, verbose_name='Название записи')),
                ('type_note', models.BooleanField(verbose_name='Онлайн/Оффлайн')),
                ('notify', models.DateTimeField(auto_now=True, null=True, verbose_name='Время уведомления о записи')),
                ('problem', models.CharField(max_length=255, verbose_name='Причина')),
                ('duration_note', models.IntegerField(blank=True, null=True, verbose_name='Длительность')),
                ('file', models.FileField(blank=True, null=True, upload_to='files_to_notes/', verbose_name='Файлы к записи')),
                ('createad_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('status', models.CharField(choices=[('Passed', 'Подтверждена'), ('In processing', 'На рассмотрении'), ('Rejected', 'Отклонена')], default='In processing', max_length=255, verbose_name='Статус записи')),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.centers')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Врач')),
                ('users_to_note', models.ManyToManyField(related_name='users_to_note', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи на запись')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
