# Generated by Django 4.2.1 on 2023-06-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_user_created_at_alter_user_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Электронный адрес'),
        ),
    ]
