# Generated by Django 5.0.1 on 2024-06-20 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_saved_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saved',
            name='user',
        ),
    ]
