# Generated by Django 5.0.1 on 2024-01-11 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_newsphotos_newsvideos_delete_newsmedia_news_images_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.group",
                verbose_name="Группа",
            ),
        ),
    ]
