# Generated by Django 4.2.1 on 2023-06-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_delete_newsimage'),
        ('api', '0020_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Описание фотографии')),
                ('image', models.ImageField(blank=True, upload_to='site_photos/', verbose_name='Фотография Сайта')),
            ],
        ),
        migrations.RenameModel(
            old_name='Desease',
            new_name='Disease',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='desease',
            new_name='disease',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='desease',
            new_name='disease',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='media/site_photos/AccauntPreview.png',
                                    upload_to='users_photos/', verbose_name='Фотография Пользователья'),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='interviews',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Фамилия'),
        ),
    ]
