# Generated by Django 4.2.1 on 2023-06-16 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_delete_newsimage'),
        ('api', '0020_alter_user_email'),
    ]

    operations = [
    ]
