# Generated by Django 4.2.1 on 2023-07-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_notes_type_note_notes_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='notify',
            field=models.DateField(blank=True, null=True, verbose_name='Время уведомления о записи'),
        ),
    ]
