# Generated by Django 5.0.1 on 2024-07-07 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_saved_user'),
        ('auth_doctor', '0002_doctor_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('title', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('online', models.BooleanField(default=False, verbose_name='Онлайн')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Длительность')),
                ('rating', models.FloatField(max_length=12, verbose_name='Цена')),
                ('center', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.center')),
                ('doctors', models.ManyToManyField(to='auth_doctor.doctor', verbose_name='Врачи')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
