# Generated by Django 4.2.1 on 2023-06-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_images_user_surname_alter_interviews_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saved',
            options={'verbose_name_plural': 'Сохраненное'},
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='media/site_photos/AccauntPreview.png', upload_to='users_photos/', verbose_name='Фотография Пользователья'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, upload_to='site_photos/', verbose_name='Фотография Сайта'),
        ),
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Описание фотографии'),
        ),
    ]
