# Generated by Django 4.2.1 on 2023-07-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_notes_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='translate_from',
            field=models.CharField(max_length=255, null=True, verbose_name='С какого языка'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='translate_to',
            field=models.CharField(max_length=255, null=True, verbose_name='На какой язык'),
        ),
    ]
