# Generated by Django 5.0.1 on 2024-07-07 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='center',
        ),
        migrations.AddField(
            model_name='service',
            name='clinic',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='api.clinic'),
            preserve_default=False,
        ),
    ]
