# Generated by Django 5.0.1 on 2024-01-13 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_user_city_user_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="country",
            name="cities",
        ),
    ]
