# Generated by Django 4.2.1 on 2023-06-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_desease_disease_rename_desease_news_disease_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='title',
            field=models.CharField(choices=[(1, 'Аденома простаты'), (2, 'Аденомы печени'), (3, 'Аднексит (воспаление придатков)'), (4, 'Акне (угревая болезнь)')], default=None, max_length=255),
        ),
    ]
