# Generated by Django 5.0.1 on 2024-07-07 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_service_center_service_clinic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='rating',
            new_name='price',
        ),
    ]
