# Generated by Django 4.2.1 on 2023-06-16 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_disease_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disease',
            options={'verbose_name_plural': 'Заболевания'},
        ),
        migrations.RemoveField(
            model_name='disease',
            name='title',
        ),
    ]
