# Generated by Django 4.2.1 on 2023-07-12 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_notes_translate_from_alter_notes_translate_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='createad_at',
            new_name='created_at',
        ),
    ]
