# Generated by Django 4.2.1 on 2023-07-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_rename_createad_at_notes_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец'),
        ),
        migrations.AddField(
            model_name='notes',
            name='time_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало '),
        ),
    ]
