# Generated by Django 5.0.1 on 2024-07-13 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_service_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='admin',
        ),
    ]
