# Generated by Django 5.0.1 on 2024-07-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_clinic_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='admin_number',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Номер Админа'),
        ),
    ]
