# Generated by Django 4.2.1 on 2023-07-13 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_notes_time_end_notes_time_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_doctor', to=settings.AUTH_USER_MODEL, verbose_name='Врач'),
        ),
    ]
