# Generated by Django 4.2.1 on 2023-07-13 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_notes_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_code',
            field=models.PositiveIntegerField(default=1, verbose_name='Код для сброса пароля'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='users_to_note',
            field=models.ManyToManyField(blank=True, related_name='users_to_note', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи на запись'),
        ),
    ]
