# Generated by Django 5.0.1 on 2024-07-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_clinic_admin_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='end_time',
            field=models.IntegerField(null=True, verbose_name='Конец работы'),
        ),
    ]
