# Generated by Django 5.0.1 on 2024-07-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_clinic_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='start_time',
            field=models.IntegerField(null=True, verbose_name='Начало работы'),
        ),
    ]
