# Generated by Django 4.2.1 on 2023-07-15 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_user_reset_code'),
        ('api', '0029_user_reset_code_alter_notes_users_to_note'),
    ]

    operations = [
    ]
