# Generated by Django 4.2.1 on 2023-07-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_merge_20230715_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='disease',
            field=models.ManyToManyField(blank=True, to='api.disease', verbose_name='Заболевания'),
        ),
    ]
