# Generated by Django 5.0.1 on 2024-01-21 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_center_country_clinic_city_clinic_country'),
        ('auth_doctor', '0015_doctor_city_doctor_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='users',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.clinic'),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='main_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_doctor.doctor'),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
