# Generated by Django 5.0.1 on 2024-01-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_remove_subscribe_users_subscribe_clinic_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={"verbose_name": "Группа", "verbose_name_plural": "Группы"},
        ),
        migrations.AlterModelOptions(
            name="subscribe",
            options={"verbose_name": "Подписка", "verbose_name_plural": "Подписки"},
        ),
        migrations.AlterField(
            model_name="user",
            name="number",
            field=models.CharField(
                blank=True, max_length=30, null=True, unique=True, verbose_name="Номер"
            ),
        ),
    ]
