# Generated by Django 5.0.1 on 2024-01-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_group_options_alter_subscribe_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='online',
            field=models.BooleanField(default=False, verbose_name='Онлайн'),
        ),
    ]
