# Generated by Django 5.0.1 on 2024-01-28 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_user_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
    ]
