# Generated by Django 5.0.1 on 2024-02-01 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_user_main_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='doctor',
        ),
    ]
