# Generated by Django 5.0.1 on 2024-02-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_center_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='country',
        ),
    ]
