# Generated by Django 5.0.1 on 2024-02-17 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_user_number_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='center',
        ),
    ]
