# Generated by Django 5.0.1 on 2024-02-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0050_subscribe_created_at_subscribe_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="access",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AddField(
            model_name="access",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Дата изменения"
            ),
        ),
    ]
