# Generated by Django 5.0.1 on 2024-02-18 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0061_rename_photos_news_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="images",
        ),
        migrations.RemoveField(
            model_name="news",
            name="videos",
        ),
    ]
