# Generated by Django 4.2.4 on 2023-09-30 11:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_doctor', '__first__'),
        ('api', '0005_remove_clinic_employees_number_clinic_employees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='centers',
            field=models.ManyToManyField(null=True, to='api.center', verbose_name='Центры'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='doctors',
            field=models.ManyToManyField(null=True, to='auth_doctor.doctor', verbose_name='Врачи'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL, verbose_name='Пациенты'),
        ),
    ]
