# Generated by Django 4.2.6 on 2023-11-21 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth_doctor", "0013_doctor_image"),
        ("api", "0016_alter_center_last_login_alter_center_password_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("social", "0002_unreadmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="unreadmessage",
            name="center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.center",
                verbose_name="Центр",
            ),
        ),
        migrations.AddField(
            model_name="unreadmessage",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth_doctor.doctor",
                verbose_name="Доктор",
            ),
        ),
        migrations.AlterField(
            model_name="unreadmessage",
            name="message",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="social.message",
                verbose_name="Сообщение",
            ),
        ),
        migrations.AlterField(
            model_name="unreadmessage",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
