# Generated by Django 4.2.1 on 2023-07-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_message_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='user1',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='user2',
            new_name='to_user',
        ),
    ]
