# Generated by Django 4.2.4 on 2023-09-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_notification_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='add',
            field=models.JSONField(default=None, null=True),
        ),
    ]
