# Generated by Django 4.2.1 on 2023-07-18 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0004_rename_user1_chat_from_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='from_user',
            new_name='user1',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='to_user',
            new_name='user2',
        ),
        migrations.RemoveField(
            model_name='message',
            name='center',
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
