# Generated by Django 5.0.1 on 2024-02-07 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0005_message_reply"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="add",
        ),
    ]
