# Generated by Django 4.2.1 on 2023-07-18 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_rename_from_user_chat_user1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='user1',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='user2',
            new_name='to_user',
        ),
    ]
