# Generated by Django 4.2.4 on 2023-09-05 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_center_observed'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorRequests',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=220, verbose_name='Номер телефона')),
                ('first_name', models.CharField(max_length=220, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=220, verbose_name='Фамилия')),
                ('city', models.CharField(max_length=220, verbose_name='Город')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.country')),
            ],
        ),
    ]
