# Generated by Django 4.2.4 on 2023-09-20 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='phone_number',
            new_name='number',
        ),
    ]
