# Generated by Django 4.2.4 on 2023-09-05 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkToInterview',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=220, verbose_name='Ссылка на интервью')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_doctor.doctorrequests')),
            ],
        ),
    ]
