# Generated by Django 5.0.1 on 2024-07-13 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_clinic_admin_number'),
        ('auth_doctor', '0002_doctor_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.center', verbose_name='Центр, в котором зарегистрирован врач'),
        ),
    ]
