# Generated by Django 4.2.4 on 2023-10-04 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_user_interest"),
        (
            "auth_doctor",
            "0004_alter_linktointerview_options_linktointerview_center_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="linktointerview",
            name="center",
        ),
        migrations.RemoveField(
            model_name="linktointerview",
            name="clinic",
        ),
        migrations.RemoveField(
            model_name="linktointerview",
            name="doctor",
        ),
        migrations.AddField(
            model_name="linktointerview",
            name="used",
            field=models.BooleanField(default=False, verbose_name="Использована"),
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        db_index=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.center",
                        verbose_name="Центр",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.clinic",
                        verbose_name="Клиника",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth_doctor.doctor",
                        verbose_name="Врач",
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth_doctor.linktointerview",
                    ),
                ),
            ],
        ),
    ]
