# Generated by Django 4.2.4 on 2023-10-06 15:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_doctor", "0008_alter_doctor_country"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="doctor",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="email",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="username",
        ),
    ]
