# Generated by Django 4.2.4 on 2023-10-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "auth_doctor",
            "0009_alter_doctor_managers_remove_doctor_date_joined_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="first_name",
            field=models.CharField(max_length=50, null=True, verbose_name="Имя"),
        ),
        migrations.AddField(
            model_name="doctor",
            name="last_name",
            field=models.CharField(max_length=50, null=True, verbose_name="Фамилия"),
        ),
    ]
