# Generated by Django 4.2.4 on 2023-10-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth_doctor', '0011_doctor_email_verification_code_doctor_reset_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.CharField(max_length=220, null=True, verbose_name='Почта'),
        ),
    ]
