# Generated by Django 4.2.6 on 2023-11-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_doctor', '0012_doctor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, default='users_photos/AccauntPreview.png', upload_to='users_photos/', verbose_name='Фотография Пользователья'),
        ),
    ]
