# Generated by Django 5.0.1 on 2024-01-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_doctor", "0014_remove_doctor_city_remove_doctor_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="city",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Город"
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="country",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Страна"
            ),
        ),
    ]
