# Generated by Django 5.0.1 on 2024-01-28 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_group_options_alter_subscribe_options_and_more'),
        ('auth_doctor', '0015_doctor_city_doctor_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.clinic', verbose_name='Клиника, где врач работает'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.CharField(blank=True, max_length=220, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='review_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Предполагаемая дата и время интервью'),
        ),
    ]
