# Generated by Django 5.0.1 on 2024-01-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_doctor', '0016_alter_doctor_clinic_alter_doctor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='online',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
