# Generated by Django 5.0.1 on 2024-02-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_doctor", "0018_alter_doctor_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AddField(
            model_name="interview",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Дата изменения"
            ),
        ),
        migrations.AddField(
            model_name="linktointerview",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AddField(
            model_name="linktointerview",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Дата изменения"
            ),
        ),
    ]
