# Generated by Django 5.0.1 on 2024-03-29 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0063_alter_newsvideos_news_newsimages_delete_newsphotos"),
        ("auth_doctor", "0019_interview_created_at_interview_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.city",
                verbose_name="Город",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.country",
                verbose_name="Страна",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="users_photos/",
                verbose_name="Фотография Пользователья",
            ),
        ),
    ]
