# Generated by Django 5.0.1 on 2024-03-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_doctor", "0020_alter_doctor_city_alter_doctor_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="image",
            field=models.ImageField(
                blank=True,
                default="users_photos/AccauntPreview.png",
                upload_to="users_photos/",
                verbose_name="Фотография Пользователья",
            ),
        ),
    ]
