# Generated by Django 5.0.1 on 2024-03-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_doctor", "0021_alter_doctor_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="users_photos/",
                verbose_name="Фотография Пользователья",
            ),
        ),
    ]
