name: Django 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v1
        with:
          python-version: 3.11
          architecture: 'x64'
      - name: Install Dependencies
        run: |
          python -m pip install poetry
          poetry config virtualenvs.create false
          poetry install
          
      - name: Run tests
        run: python manage.py test --keepdb

