name: Django 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v1
      - uses: niden/actions-memcached@v7
        with:
          python-version: 3.11
          architecture: 'x64'
      - name: Install Dependencies
        run: |
          python -m pip install "poetry>=1.3.2,<1.4.0"
          poetry env remove --all

          sudo apt-get install --reinstall python3-distutils
          poetry config virtualenvs.create false
          poetry install
      - name: Run tests
        run: |
          python manage.py test --keepdb
  build:
    needs: [run_tests]
    runs-on: ubuntu-latest
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
    steps:
      - name: Docker Login
        run:
          echo ${{  secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - uses: actions/checkout@main
      - name: Build image
        run: docker build -t ${{ secrets.DOCKER_LOGIN }}/${{secrets.DOCKER_NAME }} .
      - name: Push image
        run: docker push $LOGIN/$NAME
        

